Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/runner/miniconda3/envs/conda-build-docs/lib/python3.7/site-packages/nbclient/client.py", line 702, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 180 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['def mesh_fig(mesh, meshR, name):', '', '    fig = plt.figure(figsize=(10, 10), facecolor="none")', '    ax  = plt.subplot(111, projection=ccrs.Orthographic(central_longitude=0.0, central_latitude=0.0, globe=None))', '    ax.coastlines(color="lightgrey")']
...
['mesh_fig(cube0, cube2, "Cube")', 'mesh_fig(socc0, socc2, "SoccerBall")', '', 'mesh_fig(ring0, ring2, "Ring")', 'mesh_fig(rand0, rand2, "Random")']
-------------------

